#!/bin/sh
while read -r file
do
    case "$1" in
        "w") 
            xwallpaper --center "$file"
            echo -e "#!/bin/sh\nxwallpaper --center '$(readlink -f "$file")'" > ~/.xwallpaper
            notify-send -i "$(readlink -f "$file")" "Wallpaper changed";;
	    "r")
		    convert -rotate 90 "$file" "$file" ;;
	    "R")
		    convert -rotate -90 "$file" "$file" ;;
	    "f")
		    convert -flop "$file" "$file" ;;
        "g")	
            setsid -f gimp "$file" ;;
    esac
done

